### ISSUE TITLE
Label is not added for all pull requests

### ISSUE THREAD

**Issue by gasigo** [CodelyTV/pr-size-labeler#15]
I've noticed that the label it's not being added for every pull request. The latest pull request where the label was not added had two labels with spaces in it. May not be related though. Any idea what could be the problem? 

Thanks in advance

**Comment by rgomezcasas** [comment]
Could you paste here the output of the action? (deleting all sensitive data)

**Comment by rgomezcasas** [comment]
This was also reported in #16 with the output, so I fixed it in #17 :)

**Comment by KarimFikani** [comment]
@rgomezcasas I still don't see the label even after fix #17.

Here is my output:

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
/src/github.sh: line 12: null: unbound variable
Total modifications: 
/src/labeler.sh: line 37: [: : integer expression expected
Labeling pull request with size/xl
/src/labeler.sh: line 39: [: : integer expression expected
/src/labeler.sh: line 41: [: : integer expression expected
/src/labeler.sh: line 43: [: : integer expression expected
jq: error (at <stdin>:1): Cannot iterate over null (null)
Final labels: "size/xl"
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/issues/#edit-an-issue"
}
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/issues/comments/#create-a-comment"
}

**Comment by KarimFikani** [comment]
@rgomezcasas also getting other errors too:

Total modifications: 
Labeling pull request with size/xl
Final labels: "size/xl"
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/issues/#edit-an-issue"
}
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/issues/comments/#create-a-comment"
}

Not sure why the PR got labeled with size/xl and the PR has only +297 −98

**Comment by KarimFikani** [comment]
These errors show up when I changed 

`on: [pull_request]` to `on: [push]`

because I wanted the size labeler to run on every push and not only when creating the pull request.

**Comment by AlexBeauchemin** [comment]
I fixed the issue by adding the correct permissions to the task and commenting out the github_api_url
```
permissions:
  issues: write
  pull-requests: write
steps:
  ...
          # github_api_url: 'api.github.com'  
```

**Comment by Wolfsblvt** [comment]
> I fixed the issue by adding the correct permissions to the task and commenting out the github_api_url

Same here! Turns out, it wasn’t the github_api_url, but the permissions that did the trick.

I spent way too long trying to figure this out - why does this action specifically require `issues: write` permissions? Most other actions I use that modify PRs, including other labeling actions, work just fine with just `pull_request: write`. Any insights on why this one behaves differently?

A couple of suggestions that might help others avoid this:

1. It would be great if this was mentioned somewhere in the documentation. Happy to PR this if you'd like.
2. The action should ideally throw an error (or at least log a clear warning) when it fails due to missing permissions. Instead, I ended up going down a debugging rabbit hole when a simple “Missing required permissions” message would’ve saved me a lot of time.

**Comment by posquit0** [comment]
Same here!
